services:
  - type: web
    name: geospatial-engine-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: TEST_USERNAME
        sync: false
      - key: TEST_PASSWORD
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
